### ISSUE TITLE
Txgh Queue

### ISSUE THREAD

**Issue by camertron** [lumoslabs/txgh#56]
Hey @lumoslabs/platform,

I've got a number of PRs for you guys to look at regarding the txgh queue implementation I've been working on. It's a pretty big change (mostly new stuff), so I've tried to break it up into logical chunks. Please review in this order:
- [x] Add github event to webhook attribute classes (#50)
- [x] Add status code to transifex api errors (#51)
- [x] Publish error params (#52)
- [x] Provide ability to pass in file sha to GithubApi#update_contents (#53)
- [x] Adding Utils.deep_symbolize_keys (#54)
- [x] Queue framework boilerplate (#55)
- [x] Queue error handling (#58)
- [x] SQS Backend (#59)
- [x] API endpoint changes (#61)

[PLAT-1166](https://lumoslabs.atlassian.net/browse/PLAT-1166)
